import type {
  MetricId,
  MetricUnit,
  VisualizationId,
  WidgetInstance,
  WidgetSize,
} from "./types";

export type MetricSource = "internal" | "onlinepos" | "workfeed";

export type MetricDefinition = {
  id: MetricId;
  label: string;
  category: string;
  description: string;
  formula: string;
  sourceTables: readonly [string, ...string[]];
  source: MetricSource;
  unit: MetricUnit;
  visualizations: readonly VisualizationId[];
  defaultVisualization: VisualizationId;
  defaultSize: WidgetSize;
  sensitive?: boolean;
  shareable?: boolean;
};

const definitions = {
  wasteQuantity: {
    id: "wasteQuantity",
    label: "Waste-mængde",
    category: "Waste",
    description: "Registreret Waste i produkternes standardenhed.",
    formula: "Summen af standardmængden for aktive Waste-registreringer i perioden.",
    sourceTables: ["wasteRegistrations"],
    source: "internal",
    unit: "quantity",
    visualizations: ["kpi", "line", "bar", "area", "table"],
    defaultVisualization: "area",
    defaultSize: "2x2",
  },
  wasteRegistrations: {
    id: "wasteRegistrations",
    label: "Waste-registreringer",
    category: "Waste",
    description: "Antal aktive Waste-registreringer.",
    formula: "Antal aktive Waste-registreringer i perioden.",
    sourceTables: ["wasteRegistrations"],
    source: "internal",
    unit: "count",
    visualizations: ["kpi", "line", "bar", "area", "table"],
    defaultVisualization: "kpi",
    defaultSize: "1x1",
  },
  topWastedProducts: {
    id: "topWastedProducts",
    label: "Produkter med flest Waste-registreringer",
    category: "Waste",
    description: "Produkter sorteret efter antal Waste-registreringer.",
    formula: "Antal aktive Waste-registreringer pr. produkt i perioden, sorteret faldende (top 10).",
    sourceTables: ["wasteRegistrations"],
    source: "internal",
    unit: "count",
    visualizations: ["bar", "donut", "list", "table"],
    defaultVisualization: "list",
    defaultSize: "2x2",
  },
  wasteByCategory: {
    id: "wasteByCategory",
    label: "Waste pr. kategori",
    category: "Waste",
    description: "Waste-registreringer fordelt på produktkategori.",
    formula: "Antal aktive Waste-registreringer pr. produktkategori i perioden, sorteret faldende (top 10).",
    sourceTables: ["wasteRegistrations", "products", "categories"],
    source: "internal",
    unit: "count",
    visualizations: ["bar", "donut", "list", "table"],
    defaultVisualization: "donut",
    defaultSize: "2x2",
  },
  badDeliveries: {
    id: "badDeliveries",
    label: "Dårlige leveringer",
    category: "Leveringer",
    description: "Antal aktive registreringer af dårlige leveringer.",
    formula: "Antal aktive registreringer af dårlige leveringer i perioden.",
    sourceTables: ["badDeliveries"],
    source: "internal",
    unit: "count",
    visualizations: ["kpi", "line", "bar", "area"],
    defaultVisualization: "kpi",
    defaultSize: "1x1",
  },
  countCompliance: {
    id: "countCompliance",
    label: "Gennemførte Counts",
    category: "Count",
    description: "Andel af periodens Counts, der er indsendt.",
    formula: "Antal indsendte Counts ÷ antal Counts × 100.",
    sourceTables: ["counts"],
    source: "internal",
    unit: "percent",
    visualizations: ["kpi", "gauge", "bar"],
    defaultVisualization: "gauge",
    defaultSize: "1x1",
  },
  openCounts: {
    id: "openCounts",
    label: "Åbne Counts",
    category: "Count",
    description: "Counts, der endnu ikke er indsendt.",
    formula: "Antal Counts oprettet før måletidspunktet, som ikke er indsendt ved måletidspunktet.",
    sourceTables: ["counts"],
    source: "internal",
    unit: "count",
    visualizations: ["kpi", "list", "table"],
    defaultVisualization: "kpi",
    defaultSize: "1x1",
  },
  transfers: {
    id: "transfers",
    label: "Transfers",
    category: "Transfer",
    description: "Antal transfers i perioden.",
    formula: "Antal transfers, hvor en valgt lokation er afsender eller modtager; tælles på afsenderlokationen.",
    sourceTables: ["transfers"],
    source: "internal",
    unit: "count",
    visualizations: ["kpi", "line", "bar", "area", "table"],
    defaultVisualization: "kpi",
    defaultSize: "1x1",
  },
  itemsMoved: {
    id: "itemsMoved",
    label: "Transfermængde",
    category: "Transfer",
    description: "Samlet registreret mængde på transferlinjer.",
    formula: "Summen af transferlinjens antal × faktor til standardenhed.",
    sourceTables: ["transfers", "transferItems"],
    source: "internal",
    unit: "quantity",
    visualizations: ["kpi", "line", "bar", "area", "table"],
    defaultVisualization: "line",
    defaultSize: "2x1",
  },
  topTransferredProducts: {
    id: "topTransferredProducts",
    label: "Produkter med størst transfermængde",
    category: "Transfer",
    description: "Produkter sorteret efter registreret transfermængde.",
    formula: "Summen af transferlinjens antal × faktor til standardenhed pr. produkt i perioden, sorteret faldende (top 10).",
    sourceTables: ["transfers", "transferItems"],
    source: "internal",
    unit: "quantity",
    visualizations: ["bar", "donut", "list", "table"],
    defaultVisualization: "bar",
    defaultSize: "2x2",
  },
  staffFoodRegistrations: {
    id: "staffFoodRegistrations",
    label: "Staff food-registreringer",
    category: "Staff food",
    description: "Antal aktive Staff food-registreringer.",
    formula: "Antal aktive Staff food-registreringer i perioden.",
    sourceTables: ["staffFoodRegistrations"],
    source: "internal",
    unit: "count",
    visualizations: ["kpi", "line", "bar", "area", "table"],
    defaultVisualization: "kpi",
    defaultSize: "1x1",
  },
  staffFoodPerEmployee: {
    id: "staffFoodPerEmployee",
    label: "Staff food pr. medarbejder",
    category: "Staff food",
    description: "Registreringer fordelt på medarbejder.",
    formula: "Antal aktive Staff food-registreringer pr. medarbejder, sorteret faldende (top 10).",
    sourceTables: ["staffFoodRegistrations"],
    source: "internal",
    unit: "count",
    visualizations: ["bar", "donut", "list", "table"],
    defaultVisualization: "list",
    defaultSize: "2x2",
  },
  scheduledHours: {
    id: "scheduledHours",
    label: "Planlagte timer",
    category: "Vagtplan",
    description: "Samlede timer i den synkroniserede vagtplan.",
    formula: "Summen af max(0, sluttid − starttid) omregnet til timer.",
    sourceTables: ["scheduledShifts"],
    source: "workfeed",
    unit: "hours",
    visualizations: ["kpi", "line", "bar", "area", "table"],
    defaultVisualization: "area",
    defaultSize: "2x1",
  },
  headcountToday: {
    id: "headcountToday",
    label: "På vagt i dag",
    category: "Vagtplan",
    description: "Unikke medarbejdere med en planlagt vagt i dag.",
    formula: "Antal unikke medarbejdere med en vagt, der overlapper i dag.",
    sourceTables: ["scheduledShifts", "employees"],
    source: "workfeed",
    unit: "count",
    visualizations: ["kpi", "list", "table"],
    defaultVisualization: "kpi",
    defaultSize: "1x1",
  },
  locationComparison: {
    id: "locationComparison",
    label: "Aktivitet pr. lokation",
    category: "Sammenligning",
    description: "Samlet antal registreringer og transfers pr. lokation.",
    formula: "Antal aktive Waste-registreringer + aktive dårlige leveringer + transfers på afsenderlokationen + aktive Staff food-registreringer pr. lokation.",
    sourceTables: ["wasteRegistrations", "badDeliveries", "transfers", "staffFoodRegistrations"],
    source: "internal",
    unit: "count",
    visualizations: ["bar", "list", "table"],
    defaultVisualization: "table",
    defaultSize: "4x2",
  },
  salesRevenue: {
    id: "salesRevenue",
    label: "Omsætning",
    category: "Salg",
    description: "Samlet omsætning i perioden.",
    formula: "Summen af daglig omsætning i mindreenheder ÷ 100.",
    sourceTables: ["salesDaily"],
    source: "onlinepos",
    unit: "currency",
    visualizations: ["kpi", "line", "bar", "area", "table"],
    defaultVisualization: "kpi",
    defaultSize: "2x1",
    sensitive: true,
    shareable: true,
  },
  salesOrderCount: {
    id: "salesOrderCount",
    label: "Ordrer",
    category: "Salg",
    description: "Antal ordrer i perioden.",
    formula: "Summen af daglige ordreantal.",
    sourceTables: ["salesDaily"],
    source: "onlinepos",
    unit: "count",
    visualizations: ["kpi", "line", "bar", "area", "table"],
    defaultVisualization: "kpi",
    defaultSize: "1x1",
    sensitive: true,
    shareable: true,
  },
  averageBasket: {
    id: "averageBasket",
    label: "Gennemsnitlig kurv",
    category: "Salg",
    description: "Omsætning divideret med antal ordrer.",
    formula: "Summen af omsætning i mindreenheder ÷ summen af ordrer ÷ 100; 0 hvis der ikke er ordrer.",
    sourceTables: ["salesDaily"],
    source: "onlinepos",
    unit: "currency",
    visualizations: ["kpi", "line", "bar", "area", "table"],
    defaultVisualization: "kpi",
    defaultSize: "1x1",
    sensitive: true,
    shareable: true,
  },
} satisfies Record<MetricId, MetricDefinition>;

export const metricRegistry: Record<MetricId, MetricDefinition> = definitions;

export const metrics: MetricDefinition[] = Object.values(metricRegistry);

export const visualizationLabels: Record<VisualizationId, string> = {
  kpi: "Nøgletal",
  line: "Linjediagram",
  bar: "Søjlediagram",
  area: "Områdediagram",
  donut: "Donutdiagram",
  gauge: "Måler",
  list: "Liste",
  table: "Tabel",
};

export const sizeLabels: Record<WidgetSize, string> = {
  "1x1": "Lille",
  "1x2": "Høj",
  "2x1": "Bred",
  "2x2": "Stor",
  "4x2": "Fuld bredde",
};

export const defaultWidgets: WidgetInstance[] = [
  {
    key: "waste-registrations",
    metric: { kind: "builtin", id: "wasteRegistrations" },
    visualization: "kpi",
    size: "1x1",
    position: { column: 0, row: 0 },
  },
  {
    key: "transfers",
    metric: { kind: "builtin", id: "transfers" },
    visualization: "kpi",
    size: "1x1",
    position: { column: 1, row: 0 },
  },
  {
    key: "scheduled-hours",
    metric: { kind: "builtin", id: "scheduledHours" },
    visualization: "area",
    size: "2x1",
    position: { column: 2, row: 0 },
  },
  {
    key: "waste-over-time",
    metric: { kind: "builtin", id: "wasteQuantity" },
    visualization: "area",
    size: "2x2",
    position: { column: 0, row: 1 },
  },
  {
    key: "location-comparison",
    metric: { kind: "builtin", id: "locationComparison" },
    visualization: "table",
    size: "2x2",
    position: { column: 2, row: 1 },
  },
];
